name: Update Repos

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Deno
      uses: denoland/setup-deno@v1

    - name: Run Deno task
      run: deno task grab

    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automatically update _data/repos.json"
        commit_options: '--author="GitHub Actions <actions@github.com>"'
        branch: main
        pull_branch: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
