name: Update Repos
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  update-repos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run deno grab action
        run: deno task grab
      - uses: stefanzweifel/git-auto-commit-action@v4
      